In [1]:
import numpy as np

N=1000
D=16
K=10


data = np.random.rand(N,D)

def kmeans(data, k):
    #initialize centroids
    #Until convergence
    ## find distance to existing centroids
    ## reassign membership based on distance
    ## recompute centroids

    centroids = data[np.random.randint(0,len(data), k)] #KxD
    best_loss=1e9
    while True:
        #NxD -> Nx1xD - KxD -> NxK
        distances = np.sum((data[:, np.newaxis]-centroids)**2, axis=2)
        
        #NxK -> Nx1
        classes=np.argmin(distances,axis=1)
        mse_loss = np.sum(np.min(distances, axis=1))
        if abs(best_loss-mse_loss)<1e-3:
            break
        best_loss=mse_loss
        for idx in range(k):
            centroids[idx]=np.mean(data[classes==idx], axis=0)
        
        


# Sampling Problems

In [ ]:
#Fisher Yates
def sample_without_replacement(L, k):
    sample=L.copy()
    for i in range(k):
        j=np.random.randint(i,len(L))
        sample[i],sample[j]=sample[j],sample[i]
    return sample

#Fisher Yates w/ indexing
def sample_without_replacement_indexed(L,k):
    idx=range(0, len(L))
    for i in range(k):
        j=np.random.randint(i,len(idx))
        idx[i],idx[j]=idx[j],idx[i]
    return [L[x] for x in idx[:k]]

#Rejdction/set samp,ing k<<n
def rejection_sampling(L,k):
    samples=set()
    while len(samples)<k:
        samples.add(L[np.random.randint(0,len(L)-1)])
    return samples

#Reservoir sampling for streaming use cases
def reservoir_sampling(stream, k):
    samples=[]
    for idx, element in enumerate(iter(stream)):
        #first add k to the resrvoir
        if len(samples)<k:
            samples.append(element)
        else:
            #Sample with probability k/i+1
            j=np.random.randint(0, idx+1)
            if j<k:
                samples[j]=element
    return samples


# Sampling from a discrete distribution
def sample_discrete(L,k,discrete):
    cdf=[]
    running_sum=0
    for x in discrete:
        running_sum+=x
        cdf.append(running_sum)
    
    samples=[]
    while len(samples)<k:
        r=np.random.uniform(0,running_sum)
        for i,x in enumerate(cdf):
            if r<=x:
                samples.append(L[i])
                break
    return samples




        






In [ ]:
matrix_A = [
    [1, 0, 2],
    [0, 3, 0], 
    [4, 0, 5]
]

matrix_B = [
    [0, 1, 0],
    [2, 0, 3],
    [0, 4, 0]
]

def dense_to_sparse(matrix):
    csr_values=[]
    csr_cols=[]
    csr_rows=[0]
    for r in range(len(matrix)):
        for c in range(len(matrix[r])):
            if matrix[r][c]!=0:
                csr_values.append(matrix[r][c])
                csr_cols.append(c)
        csr_rows.append(len(csr_values))
    csr_matrix=(csr_values, csr_cols, csr_rows)
    print("CSR:",csr_matrix)
    print(sparse_to_dense(csr_matrix))
    return (csr_matrix)

def sparse_to_dense(csr):
    csr_values, csr_cols, csr_rows = csr
    matrix=np.zeros(((len(csr_rows)-1),(max(csr_cols)+1)), dtype=int)
    for idx in range(len(csr_rows)-1):
        v=csr_values[csr_rows[idx]:csr_rows[idx+1]]
        c=csr_cols[csr_rows[idx]:csr_rows[idx+1]]
        for x,y in zip(c,v):
            matrix[idx][x]=y
    return matrix

def sparse_get_element(csr, i,j):
    (csr_values, csr_cols, csr_rows)=csr
    v=csr_values[csr_rows[i]:csr_rows[i+1]]
    c=csr_cols[csr_rows[i]:csr_rows[i+1]]
    for x,y in zip(v,c):
        if y==j:
            return v
    return 0





csr_A=dense_to_sparse(matrix_A)
csr_B=dense_to_sparse(matrix_B)



CSR: ([1, 2, 3, 4, 5], [0, 2, 1, 0, 2], [0, 2, 3, 5])
[[1 0 2]
 [0 3 0]
 [4 0 5]]
CSR: ([1, 2, 3, 4], [1, 0, 2, 1], [0, 1, 3, 4])
[[0 1 0]
 [2 0 3]
 [0 4 0]]
